spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/attendance_db
    username: postgres
    password: postgres_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

springdoc:
  swagger-ui:
    tagsSorter: alpha
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
    use-fqn: true